language: bash

addons:
  apt:
    # https://github.com/koalaman/shellcheck/wiki/TravisCI
    sources:
    - debian-sid
    packages:
    - shellcheck
    - python-docutils # Needed for rst2man

before_install:
  - export PREFIX=$HOME/opt
  - mkdir -p $PREFIX/bin
  - export PATH=$PREFIX/bin:$PATH


install:
  # Install BUTT for Bash testing
  - wget https://github.com/InternetGuru/butt/archive/dev.tar.gz -O /tmp/butt.tar.gz
  - tar -xvf /tmp/butt.tar.gz
  - pushd butt-dev && ./configure && make && compiled/install && popd

before_script:
 - git config --global user.email "test@test.cz"
 - git config --global user.name "test"
 - ./configure && make && compiled/install

script:
 - shellcheck gf
 - butt test/test.butt

matrix:
  fast_finish: true
