language: bash
sudo: required

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

before_install:
 - sudo pip install docutils

install:
 - "sudo ./configure && sudo PREFIX=/usr make && sudo compiled/install"

script:
 - shellcheck gf
 - cd test
 - git config --global user.email "test@test.cz"
 - git config --global user.name "test"
 - ./run

matrix:
  fast_finish: true