language: bash
sudo: required

addons:
  apt:
    sources:
    - debian-sid
    # packages:
    # - shellcheck

before_install:
 - sudo pip install docutils

install:
 - "sudo ./configure && sudo PREFIX=/usr make && sudo compiled/install"

script:
 - shellcheck gf
 - test/run -c

matrix:
  fast_finish: true